#!/bin/bash 
tomcat_home=/usr/local/tomcat
SHUTDOWN=$tomcat_home/bin/shutdown.sh
STARTTOMCAT=$tomcat_home/bin/startup.sh
case $1 in
start)
echo "启动$tomcat_home"
$STARTTOMCAT
;;
stop)
echo "关闭$tomcat_home"
$SHUTDOWN
pidlist=`ps -ef |grep java |grep -v "grep"|awk '{print $2}'`
kill -9 $pidlist
;;
restart)
echo "关闭$tomcat_home"
$SHUTDOWN
pidlist=`ps -ef |grep java |grep -v "grep"|awk '{print $2}'`
kill -9 $pidlist
sleep 5
echo "启动$tomcat_home"
$STARTTOMCAT
;;
esac

